support Mac pbcopy/pbpaste

diff --git a/common/.local/bin/cb b/common/.local/bin/cb
--- a/common/.local/bin/cb
+++ b/common/.local/bin/cb
@@ -8,17 +8,16 @@ GREEN=$'\e[0;32m'
 YELLOW=$'\e[1;33m'
 NORMAL=$'\e[0m'
 
-mode=copy
-while getopts 'hp' opt; do
+mode=""
+while getopts "chp" opt; do
     case $opt in
-        p)
-            mode=paste
-            ;;
+        c) mode=copy ;;
+        p) mode=paste ;;
         h | \?)
             echo "Copies a string or the contents of a file to the clipboard."
-            echo "Usage: cb FILENAME..."
+            echo "Usage: cb [-c [FILENAME...]] [-p]"
             echo "       ... | cb"
-            echo "       cb -p | ..."
+            echo "       cb | ..."
             if [[ $opt == "?" ]]; then
                 exit 1
             else
@@ -29,41 +28,77 @@ while getopts 'hp' opt; do
 done
 shift $((OPTIND - 1))
 
-# TODO: check for Mac pbcopy/pbpaste
-if ! type xclip >/dev/null 2>&1; then
-    echo "${RED}ERROR: xclip not installed${NORMAL}" >&2
-    exit 1
+
+if [[ -z $mode ]]; then
+    # Attempt to auto-detect intended behavior from context:
+    # - If there are input file arguments, copy from them
+    # - If stdin is being piped from another program, copy from that
+    # - Otherwise, paste
+    if [[ $# -ge 1 || ! -t 0 ]]; then
+        mode=copy
+    else
+        mode=paste
+    fi
 fi
+
+# Detect the program(s) to use
+cb_type="<unknown>"
+if type -t xclip >/dev/null; then
+    # Linux under X Windows
+    cb_type=x
+elif type -t pbcopy >/dev/null; then
+    # Mac
+    cb_type=mac
+else
+    echo "${RED}ERROR: neither xclip nor pbcopy/pbpaste installed${NORMAL}" >&2
+    exit 2
+fi
+
 
 if [[ $mode == "paste" ]]; then
-    xclip -out -selection clipboard
-    exit
-fi
-
-if ! tty -s; then
-    input=$(< /dev/stdin)
-else
-    input=""
-    if [[ $# -eq 0 ]]; then
-        args=(-)
+    if [[ $cb_type == "x" ]]; then
+        xclip -out -selection clipboard
+    elif [[ $cb_type == "mac" ]]; then
+        pbpaste
     else
-        args=("$@")
+        echo "${RED}ERROR: unknown clipboard type: ${cb_type}${NORMAL}" >&2
+        exit 2
+    fi
+else
+    # read all input from stdin or specified files
+    if ! tty -s; then
+        input=$(< /dev/stdin)
+    else
+        input=""
+        if [[ $# -eq 0 ]]; then
+            args=(-)
+        else
+            args=("$@")
+        fi
+
+        for arg in "${args[@]}"; do
+            if [[ $arg == "-" ]]; then
+                input="$input$(< /dev/stdin)"
+            else
+                input="$input$(< $arg)"
+            fi
+        done
     fi
 
-    for arg in "${args[@]}"; do
-        if [[ $arg == "-" ]]; then
-            input="$input$(< /dev/stdin)"
-        else
-            input="$input$(< $arg)"
-        fi
-    done
-fi
+    # copy it to the clipboard
+    if [[ $cb_type == "x" ]]; then
+        xclip -in -selection clipboard <<< "$input"
+    elif [[ $cb_type == "mac" ]]; then
+        pbcopy <<< "$input"
+    else
+        echo "${RED}ERROR: unknown clipboard type: ${cb_type}${NORMAL}" >&2
+        exit 2
+    fi
 
-echo -n "$input" | xclip -in -selection clipboard
-
-# format for display
-input=$(tr '\n' ' ' <<<"$input")
-if [[ ${#input} -gt 80 ]]; then
-    input="$(cut -c1-80 <<<"$input")${YELLOW}...${NORMAL}"
+    # format for display
+    formatted=$(tr '\n' ' ' <<<"$input")
+    if [[ ${#formatted} -gt 80 ]]; then
+        formatted="$(cut -c1-80 <<<"$formatted")${YELLOW}...${NORMAL}"
+    fi
+    echo "${GREEN}Copied to clipboard:${NORMAL} $formatted" >&2
 fi
-echo "${GREEN}Copied to clipboard:${NORMAL} $input"
